name: pyinstaller

on:
  release:
    types: [published]

jobs:
build:
   strategy:
      matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]

   runs-on: ${{ matrix.os }}

   steps:
      - name: Check-out repository
      uses: actions/checkout@v3

      - name: Setup Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.11'
         cache: 'pipenv'

      - name: Install your Dependencies
      run: |
         pip install pipenv
         pipenv install -d

      - name: Build Executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
         nuitka-version: main
         script-name: ./app/main.py
         onefile: true

      - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: ${{ runner.os }} Build
         path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*

